# Generated by Django 4.1.7 on 2023-03-05 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=25)),
                ("description", models.TextField()),
                (
                    "pub_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 3, 5, 4, 23, 57, 217658, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=25)),
                ("description", models.TextField()),
                (
                    "pub_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 3, 5, 4, 23, 57, 243302, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="registrationdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
            ],
        ),
    ]
